name: Deploy Infotech Website
on: # This is a Event. A push is a event.
    push:
        branches:
            - New_Infotech
permissions: 
  contents: write # Allowing GITHUB_TOKEN to be access
jobs: # A job is a set of steos that are executed in a specified enviroment. In our case is Ubuntu
  build:
    runs-on: ubuntu-latest

    steps: # Every step runs on its own isolated shell session
      - name: Checkout code # Clones the repository into the VM(runner) where the workflow is running. Without this step the runner will not have access the the proyect code
        uses: actions/checkout@v3

      - name: Setup Node.js # Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15'

      - name: Install Dependencies
        run: |
          cd infotech
          npm install

      - name: Build Infotech Website #Builds the optimized, production ready version of the Reac App(Infotech Project)
        run: |
          cd infotech
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: infotech/dist
          cname: infotech-uiprb.com  # Adding cname file